/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Audit Domain Use Cases
 * 
 * List of all use case names for the audit domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const AUDIT_USE_CASES = [
  "executeCreateAdviceAuditExport",
  "executeGetAdviceAuditExport",
  "executeListAdviceAuditExports"
] as const;
