/**
 * ExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportRepository Port
 *
 * DDD: Application port for exportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAdviceAuditExportInput, CreateAdviceAuditExportOutput, GetAdviceAuditExportInput, GetAdviceAuditExportOutput, ListAdviceAuditExportsInput, ListAdviceAuditExportsOutput } from "../dto/export.dto";
export interface ExportRepository {
  listAdviceAuditExports(input: ListAdviceAuditExportsInput): Promise<ListAdviceAuditExportsOutput>;
  createAdviceAuditExport(input: CreateAdviceAuditExportInput): Promise<CreateAdviceAuditExportOutput>;
  getAdviceAuditExport(input: GetAdviceAuditExportInput): Promise<GetAdviceAuditExportOutput>;
}

export type { CreateAdviceAuditExportInput, CreateAdviceAuditExportOutput, GetAdviceAuditExportInput, GetAdviceAuditExportOutput, ListAdviceAuditExportsInput, ListAdviceAuditExportsOutput } from "../dto/export.dto";
