/**
 * RiskParameter Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/recommendations.openapi.types.js";
import { schemas } from "../schemas/recommendations.schemas.js";

/**
 * Entity: RiskParameterEntity
 * Description: Represents the RiskParameter domain model.
 * Source: schemas.RiskParameterSet
 * Type: Persisted Entity (x-dynamodb)
 */
export const RiskParameterEntitySchema = schemas.RiskParameterSet;
export type RiskParameterEntity = components["schemas"]["RiskParameterSet"];
