/**
 * ModelVersion DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ModelVersion DTOs
 *
 * DDD: Application DTOs for ModelVersion use cases.
 */

import type { CreateModelVersionRequestInput, GetModelVersionParams } from "@veltara/core/strategies/types";

export type ListModelVersionsInput = {};

export type CreateModelVersionInput = CreateModelVersionRequestInput;

export type GetModelVersionInput = GetModelVersionParams;

export type ListModelVersionsOutput = {};

export type CreateModelVersionOutput = {};

export type GetModelVersionOutput = {};
