/**
 * Strategy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Strategy DTOs
 *
 * DDD: Application DTOs for Strategy use cases.
 */

import type { CreateStrategyRequestInput, GetStrategyParams, ListStrategiesParams, UpdateStrategyParams, UpdateStrategyRequestInput } from "@veltara/core/strategies/types";

export type ListStrategiesInput = ListStrategiesParams;

export type CreateStrategyInput = CreateStrategyRequestInput;

export type GetStrategyInput = GetStrategyParams;

export type UpdateStrategyInput = UpdateStrategyParams & UpdateStrategyRequestInput;

export type ListStrategiesOutput = {};

export type CreateStrategyOutput = {};

export type GetStrategyOutput = {};

export type UpdateStrategyOutput = {};
