/**
 * Routes for Gate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { decideRecommendationGate, getGateDecision, listGateDecisions } from "../handlers/gate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function gateRoutes(fastify: FastifyInstance) {
  // GET /v1/gates (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/gates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGatesDependenciesForRequest();
        await listGateDecisions(request, reply, deps);
      });
    }
  );


  // GET /v1/gates/{gateDecisionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/gates/:gateDecisionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { gateDecisionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGatesDependenciesForRequest();
        await getGateDecision(request, reply, deps);
      });
    }
  );


  // POST /v1/recommendations/{recommendationId}/gate (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/recommendations/:recommendationId/gate",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { recommendationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGatesDependenciesForRequest();
        await decideRecommendationGate(request, reply, deps);
      });
    }
  );


}
