/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Strategies Domain Use Cases
 * 
 * List of all use case names for the strategies domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const STRATEGIES_USE_CASES = [
  "executeCreateAdvisor",
  "executeCreateModelVersion",
  "executeCreateStrategy",
  "executeGetAdvisor",
  "executeGetModelVersion",
  "executeGetStrategy",
  "executeListAdvisors",
  "executeListModelVersions",
  "executeListStrategies",
  "executeUpdateAdvisor",
  "executeUpdateStrategy"
] as const;
