/**
 * Repository interface for Advisor
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AdvisorEntity
} from "../models/advisor.entity.js";
import type {
  Advisor,
  UpdateAdvisorRequestInput
} from "../types/index.js";
/**
 * AdvisorRepository Interface
 */
export interface AdvisorRepository extends CreateUpdateReadRepository<AdvisorEntity, Advisor, UpdateAdvisorRequestInput, string, Record<string, never>> {

}
