/**
 * Repository interface for Strategy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  StrategyEntity
} from "../models/strategy.entity.js";
import type {
  ListStrategiesParams,
  StrategyPackage,
  UpdateStrategyRequestInput
} from "../types/index.js";
/**
 * StrategyRepository Interface
 */
export interface StrategyRepository extends CreateUpdateReadRepository<StrategyEntity, StrategyPackage, UpdateStrategyRequestInput, string, ListStrategiesParams> {

}
