/**
 * ModelVersionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ModelVersionRepository Port
 *
 * DDD: Application port for modelversionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateModelVersionInput, CreateModelVersionOutput, GetModelVersionInput, GetModelVersionOutput, ListModelVersionsInput, ListModelVersionsOutput } from "../dto/model-version.dto";
export interface ModelVersionRepository {
  listModelVersions(input: ListModelVersionsInput): Promise<ListModelVersionsOutput>;
  createModelVersion(input: CreateModelVersionInput): Promise<CreateModelVersionOutput>;
  getModelVersion(input: GetModelVersionInput): Promise<GetModelVersionOutput>;
}

export type { CreateModelVersionInput, CreateModelVersionOutput, GetModelVersionInput, GetModelVersionOutput, ListModelVersionsInput, ListModelVersionsOutput } from "../dto/model-version.dto";
