/**
 * StrategyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StrategyRepository Port
 *
 * DDD: Application port for strategyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateStrategyInput, CreateStrategyOutput, GetStrategyInput, GetStrategyOutput, ListStrategiesInput, ListStrategiesOutput, UpdateStrategyInput, UpdateStrategyOutput } from "../dto/strategy.dto";
export interface StrategyRepository {
  listStrategies(input: ListStrategiesInput): Promise<ListStrategiesOutput>;
  createStrategy(input: CreateStrategyInput): Promise<CreateStrategyOutput>;
  getStrategy(input: GetStrategyInput): Promise<GetStrategyOutput>;
  updateStrategy(input: UpdateStrategyInput): Promise<UpdateStrategyOutput>;
}

export type { CreateStrategyInput, CreateStrategyOutput, GetStrategyInput, GetStrategyOutput, ListStrategiesInput, ListStrategiesOutput, UpdateStrategyInput, UpdateStrategyOutput } from "../dto/strategy.dto";
