/**
 * Contract DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Contract DTOs
 *
 * DDD: Application DTOs for Contract use cases.
 */

import type { CreateMarketplaceContractRequestInput, GetMarketplaceContractParams, ListMarketplaceContractsParams } from "@veltara/core/marketplace/types";

export type ListMarketplaceContractsInput = ListMarketplaceContractsParams;

export type CreateMarketplaceContractInput = CreateMarketplaceContractRequestInput;

export type GetMarketplaceContractInput = GetMarketplaceContractParams;

export type ListMarketplaceContractsOutput = {};

export type CreateMarketplaceContractOutput = {};

export type GetMarketplaceContractOutput = {};
