/**
 * GetFreezeOrder handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFreezeOrder } from "@veltara/api-server/domains/freezes/handlers";
import type { FreezesDDDDependencies } from "@veltara/api-server/domains/freezes";
import { createFreeze as createFreezeEntity } from "@veltara/factories/freezes";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { FREEZES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFreezeOrder", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FreezesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FreezesDDDDependencies>(
      FREEZES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createFreezeEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFreezeOrder, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { freezeId: entity.id };

    await getFreezeOrder(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFreezeOrder.execute).toHaveBeenCalledWith(expect.objectContaining({ freezeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { freezeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFreezeOrder, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFreezeOrder(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
