/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-freeze-order.handler.test.js";
export * from "./get-freeze-order.handler.test.js";
export * from "./list-freeze-orders.handler.test.js";
