/**
 * LiftFreezeOrder handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { liftFreezeOrder } from "@veltara/api-server/domains/freezes/handlers";
import type { FreezesDDDDependencies } from "@veltara/api-server/domains/freezes";
import { createLift as createLiftEntity } from "@veltara/factories/freezes";
import { createCreateLiftRequest } from "@veltara/factories/freezes";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { FREEZES_USE_CASES } from "../__factories__/use-cases.js";

describe("LiftFreezeOrder", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FreezesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FreezesDDDDependencies>(
      FREEZES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateLiftRequest();
    const entity = createLiftEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeLiftFreezeOrder, "execute").mockResolvedValue(useCaseResult);

    await liftFreezeOrder(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeLiftFreezeOrder.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
