/**
 * Routes for Contract
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createMarketplaceContract, getMarketplaceContract, listMarketplaceContracts } from "../handlers/contract.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function contractRoutes(fastify: FastifyInstance) {
  // POST /v1/marketplace/contracts (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/marketplace/contracts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketplaceDependenciesForRequest();
        await createMarketplaceContract(request, reply, deps);
      });
    }
  );


  // GET /v1/marketplace/contracts (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/marketplace/contracts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketplaceDependenciesForRequest();
        await listMarketplaceContracts(request, reply, deps);
      });
    }
  );


  // GET /v1/marketplace/contracts/{contractId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/marketplace/contracts/:contractId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { contractId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMarketplaceDependenciesForRequest();
        await getMarketplaceContract(request, reply, deps);
      });
    }
  );


}
