/**
 * SuitabilityPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SuitabilityPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SuitabilityPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SuitabilityPolicyRepository,
} from "@veltara/services/profiles";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SuitabilityPolicyRepositoryDdb } from "./suitability-policy-repository.ddb.js";

/**
 * SuitabilityPolicyRepositoryAdapter
 *
 * Implements SuitabilityPolicyRepository port for infrastructure layer.
 */
export class SuitabilityPolicyRepositoryAdapter implements SuitabilityPolicyRepository {
  private readonly ddb: SuitabilityPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SuitabilityPolicyRepositoryDdb(this.dynamoClient);
  }

  async listSuitabilityPolicies(input: Parameters<SuitabilityPolicyRepository['listSuitabilityPolicies']>[0]): Promise<Awaited<ReturnType<SuitabilityPolicyRepository['listSuitabilityPolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSuitabilityPolicies(input);
  }

  async createSuitabilityPolicy(input: Parameters<SuitabilityPolicyRepository['createSuitabilityPolicy']>[0]): Promise<Awaited<ReturnType<SuitabilityPolicyRepository['createSuitabilityPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createSuitabilityPolicy(input);
  }

  async getSuitabilityPolicy(input: Parameters<SuitabilityPolicyRepository['getSuitabilityPolicy']>[0]): Promise<Awaited<ReturnType<SuitabilityPolicyRepository['getSuitabilityPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSuitabilityPolicy(input);
  }

  async upsertSuitabilityPolicy(input: Parameters<SuitabilityPolicyRepository['upsertSuitabilityPolicy']>[0]): Promise<Awaited<ReturnType<SuitabilityPolicyRepository['upsertSuitabilityPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.upsertSuitabilityPolicy(input);
  }
}
