/**
 * GetProfile DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetClientProfileParams } from "@veltara/core/profiles";

export function createGetProfileRequest(overrides: Partial<GetClientProfileParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
