/**
 * CreateStrategy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createStrategy } from "@veltara/api-server/domains/strategies/handlers";
import type { StrategiesDDDDependencies } from "@veltara/api-server/domains/strategies";
import { createStrategy as createStrategyEntity } from "@veltara/factories/strategies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { STRATEGIES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateStrategy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: StrategiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<StrategiesDDDDependencies>(
      STRATEGIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createStrategyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateStrategy, "execute").mockResolvedValue(useCaseResult);

    await createStrategy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateStrategy.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
