/**
 * UpdateStrategy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateStrategy } from "@veltara/api-server/domains/strategies/handlers";
import type { StrategiesDDDDependencies } from "@veltara/api-server/domains/strategies";
import { createStrategy as createStrategyEntity } from "@veltara/factories/strategies";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { STRATEGIES_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateStrategy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: StrategiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<StrategiesDDDDependencies>(
      STRATEGIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createStrategyEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { strategyId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateStrategy, "execute").mockResolvedValue(useCaseResult);

    await updateStrategy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateStrategy.execute).toHaveBeenCalledWith(expect.objectContaining({ strategyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
