/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as auditRoutes from "../../domains/audit/routes/index.js";
import * as freezesRoutes from "../../domains/freezes/routes/index.js";
import * as gatesRoutes from "../../domains/gates/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as marketplaceRoutes from "../../domains/marketplace/routes/index.js";
import * as profilesRoutes from "../../domains/profiles/routes/index.js";
import * as recommendationsRoutes from "../../domains/recommendations/routes/index.js";
import * as strategiesRoutes from "../../domains/strategies/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "audit", mod: auditRoutes },
  { domain: "freezes", mod: freezesRoutes },
  { domain: "gates", mod: gatesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "signupRoutes", "sessionRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "marketplace", mod: marketplaceRoutes },
  { domain: "profiles", mod: profilesRoutes },
  { domain: "recommendations", mod: recommendationsRoutes },
  { domain: "strategies", mod: strategiesRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
