/**
 * Routes for SuitabilityPolicy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createSuitabilityPolicy, getSuitabilityPolicy, listSuitabilityPolicies, upsertSuitabilityPolicy } from "../handlers/suitability-policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function suitabilityPolicyRoutes(fastify: FastifyInstance) {
  // POST /v1/suitability-policies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/suitability-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProfilesDependenciesForRequest();
        await createSuitabilityPolicy(request, reply, deps);
      });
    }
  );


  // GET /v1/suitability-policies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/suitability-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProfilesDependenciesForRequest();
        await listSuitabilityPolicies(request, reply, deps);
      });
    }
  );


  // GET /v1/suitability-policies/{policyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/suitability-policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProfilesDependenciesForRequest();
        await getSuitabilityPolicy(request, reply, deps);
      });
    }
  );


  // PUT /v1/suitability-policies/{policyId} (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/suitability-policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getProfilesDependenciesForRequest();
        await upsertSuitabilityPolicy(request, reply, deps);
      });
    }
  );


}
