/**
 * Gate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/gates.openapi.types.js";
import { schemas } from "../schemas/gates.schemas.js";

/**
 * Entity: GateEntity
 * Description: Represents the Gate domain model.
 * Source: schemas.GateDecision
 * Type: Persisted Entity (x-dynamodb)
 */
export const GateEntitySchema = schemas.GateDecision;
export type GateEntity = components["schemas"]["GateDecision"];
