/**
 * AdvisorRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdvisorRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AdvisorRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AdvisorRepository,
} from "@veltara/services/strategies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AdvisorRepositoryDdb } from "./advisor-repository.ddb.js";

/**
 * AdvisorRepositoryAdapter
 *
 * Implements AdvisorRepository port for infrastructure layer.
 */
export class AdvisorRepositoryAdapter implements AdvisorRepository {
  private readonly ddb: AdvisorRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AdvisorRepositoryDdb(this.dynamoClient);
  }

  async listAdvisors(input: Parameters<AdvisorRepository['listAdvisors']>[0]): Promise<Awaited<ReturnType<AdvisorRepository['listAdvisors']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAdvisors(input);
  }

  async createAdvisor(input: Parameters<AdvisorRepository['createAdvisor']>[0]): Promise<Awaited<ReturnType<AdvisorRepository['createAdvisor']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAdvisor(input);
  }

  async getAdvisor(input: Parameters<AdvisorRepository['getAdvisor']>[0]): Promise<Awaited<ReturnType<AdvisorRepository['getAdvisor']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAdvisor(input);
  }

  async updateAdvisor(input: Parameters<AdvisorRepository['updateAdvisor']>[0]): Promise<Awaited<ReturnType<AdvisorRepository['updateAdvisor']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateAdvisor(input);
  }
}
