/**
 * StrategyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StrategyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements StrategyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  StrategyRepository,
} from "@veltara/services/strategies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { StrategyRepositoryDdb } from "./strategy-repository.ddb.js";

/**
 * StrategyRepositoryAdapter
 *
 * Implements StrategyRepository port for infrastructure layer.
 */
export class StrategyRepositoryAdapter implements StrategyRepository {
  private readonly ddb: StrategyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new StrategyRepositoryDdb(this.dynamoClient);
  }

  async listStrategies(input: Parameters<StrategyRepository['listStrategies']>[0]): Promise<Awaited<ReturnType<StrategyRepository['listStrategies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listStrategies(input);
  }

  async createStrategy(input: Parameters<StrategyRepository['createStrategy']>[0]): Promise<Awaited<ReturnType<StrategyRepository['createStrategy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createStrategy(input);
  }

  async getStrategy(input: Parameters<StrategyRepository['getStrategy']>[0]): Promise<Awaited<ReturnType<StrategyRepository['getStrategy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getStrategy(input);
  }

  async updateStrategy(input: Parameters<StrategyRepository['updateStrategy']>[0]): Promise<Awaited<ReturnType<StrategyRepository['updateStrategy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateStrategy(input);
  }
}
