/**
 * Repository interface for Recommendation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RecommendationEntity
} from "../models/recommendation.entity.js";
import type {
  ListClientRecommendationsParams,
  Recommendation
} from "../types/index.js";
/**
 * RecommendationRepository Interface
 */
export interface RecommendationRepository extends CreateReadRepository<RecommendationEntity, Recommendation, string, ListClientRecommendationsParams> {

}
