/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the recommendations domain.
 * Use these factories in tests to create test data.
 */

export { createRecommendation } from "./recommendation/entity/recommendation.entity.factory.js";
export { createRiskParameter } from "./risk-parameter/entity/risk-parameter.entity.factory.js";
