/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Recommendations Domain Use Cases
 * 
 * List of all use case names for the recommendations domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const RECOMMENDATIONS_USE_CASES = [
  "executeCreateClientRecommendation",
  "executeGetRecommendation",
  "executeGetRecommendationRiskParameters",
  "executeListClientRecommendations",
  "executeUpsertRecommendationRiskParameters"
] as const;
