/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { exportRoutes } from "./export.routes.js";
