/**
 * ExecuteListFreezeOrders - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFreezeOrders Use Case
 *
 * DDD: Application use case for list Freeze.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFreezeOrdersInput, ListFreezeOrdersOutput } from "../dto/freeze.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { FreezeRepository } from "../ports";

export class ExecuteListFreezeOrders {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly freeze: FreezeRepository
  ) {}

  async execute(input: ListFreezeOrdersInput): Promise<ListFreezeOrdersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.frzId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.freeze.listFreezeOrders({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFreezeOrdersOutput;
  }
}
