/**
 * SuitabilityPolicy Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/profiles.openapi.types.js";
import { schemas } from "../schemas/profiles.schemas.js";

/**
 * Entity: SuitabilityPolicyEntity
 * Description: Represents the SuitabilityPolicy domain model.
 * Source: schemas.SuitabilityPolicy
 * Type: Persisted Entity (x-dynamodb)
 */
export const SuitabilityPolicyEntitySchema = schemas.SuitabilityPolicy;
export type SuitabilityPolicyEntity = components["schemas"]["SuitabilityPolicy"];
