/**
 * GetSuitabilityPolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSuitabilityPolicy } from "@veltara/api-server/domains/profiles/handlers";
import type { ProfilesDDDDependencies } from "@veltara/api-server/domains/profiles";
import { createSuitabilityPolicy as createSuitabilityPolicyEntity } from "@veltara/factories/profiles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { PROFILES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSuitabilityPolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProfilesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProfilesDDDDependencies>(
      PROFILES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createSuitabilityPolicyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSuitabilityPolicy, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { policyId: entity.id };

    await getSuitabilityPolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSuitabilityPolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ policyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { policyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSuitabilityPolicy, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSuitabilityPolicy(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
