/**
 * ListSuitabilityPolicies handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listSuitabilityPolicies } from "@veltara/api-server/domains/profiles/handlers";
import type { ProfilesDDDDependencies } from "@veltara/api-server/domains/profiles";
import { createSuitabilityPolicy as createSuitabilityPolicyEntity } from "@veltara/factories/profiles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { PROFILES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListSuitabilityPolicies", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProfilesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProfilesDDDDependencies>(
      PROFILES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createSuitabilityPolicyEntity({ orgId }),
      createSuitabilityPolicyEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListSuitabilityPolicies, "execute").mockResolvedValue(useCaseResult);

    await listSuitabilityPolicies(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListSuitabilityPolicies.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
