/**
 * ExecuteCreateAdviceAuditExport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audit
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateAdviceAuditExport Use Case
 *
 * DDD: Application use case for create Export.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateAdviceAuditExportInput, CreateAdviceAuditExportOutput } from "../dto/export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { ExportRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateAdviceAuditExport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportRepo: ExportRepository
  ) {}

  async execute(input: CreateAdviceAuditExportInput): Promise<CreateAdviceAuditExportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: clientId, from, to
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.from) {
      throw new ValidationError("from is required");
    }
    if (!input.to) {
      throw new ValidationError("to is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (audit domain)
    const entityId = this.idGenerator.audId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.exportRepo.createAdviceAuditExport({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateAdviceAuditExportOutput;
  }
}
