/**
 * ModelVersion Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ModelVersionEntity } from "@veltara/core/strategies/models/index.js";
import { strategiesSchemas } from "@veltara/core/strategies";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "stg";

export function createModelVersion(overrides: Partial<ModelVersionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `mdl_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "active",
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return strategiesSchemas.ModelVersion.parse(raw);
}

export function modelVersionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createModelVersion(overrides));
}
