/**
 * ExecuteListMarketplaceContracts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListMarketplaceContracts Use Case
 *
 * DDD: Application use case for list Contract.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListMarketplaceContractsInput, ListMarketplaceContractsOutput } from "../dto/contract.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { ContractRepository } from "../ports";

export class ExecuteListMarketplaceContracts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contract: ContractRepository
  ) {}

  async execute(input: ListMarketplaceContractsInput): Promise<ListMarketplaceContractsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mktId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.contract.listMarketplaceContracts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListMarketplaceContractsOutput;
  }
}
