/**
 * Strategies DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Strategies Domain Module - Composition root
 *
 * DDD: Composition root for strategies domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AdvisorRepositoryAdapter,
  ModelVersionRepositoryAdapter,
  StrategyRepositoryAdapter,
} from "@veltara/adapters/strategies";
import { getIdGeneratorService } from "@veltara/adapters";
import type { AdapterDynamoDBClient } from "@veltara/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAdvisor,
  ExecuteCreateModelVersion,
  ExecuteCreateStrategy,
  ExecuteGetAdvisor,
  ExecuteGetModelVersion,
  ExecuteGetStrategy,
  ExecuteListAdvisors,
  ExecuteListModelVersions,
  ExecuteListStrategies,
  ExecuteUpdateAdvisor,
  ExecuteUpdateStrategy,
} from "@veltara/services/strategies/usecases";
// Ports (interfaces)
import type {
  AdvisorRepository,
  ModelVersionRepository,
  StrategyRepository,
} from "@veltara/services/strategies/ports";

export interface StrategiesDomainModule {
  repos: {
    advisors: AdvisorRepository;
    modelVersions: ModelVersionRepository;
    strategies: StrategyRepository;
  };
  useCases: {
    advisors: {
      create: ExecuteCreateAdvisor;
      get: ExecuteGetAdvisor;
      list: ExecuteListAdvisors;
      update: ExecuteUpdateAdvisor;
    };
    modelVersions: {
      create: ExecuteCreateModelVersion;
      get: ExecuteGetModelVersion;
      list: ExecuteListModelVersions;
    };
    strategies: {
      create: ExecuteCreateStrategy;
      get: ExecuteGetStrategy;
      list: ExecuteListStrategies;
      update: ExecuteUpdateStrategy;
    };
  };
}

export function buildStrategiesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): StrategiesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      advisors?: AdvisorRepository;
      modelVersions?: ModelVersionRepository;
      strategies?: StrategyRepository;
    } = {};

    obj.advisors = new AdvisorRepositoryAdapter(dynamoClient);
    obj.modelVersions = new ModelVersionRepositoryAdapter(dynamoClient);
    obj.strategies = new StrategyRepositoryAdapter(dynamoClient);
    return {
      advisors: obj.advisors!,
      modelVersions: obj.modelVersions!,
      strategies: obj.strategies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    advisors: {
      create: new ExecuteCreateAdvisor(executionContext, idGenerator, repos.advisors),
      get: new ExecuteGetAdvisor(executionContext, idGenerator, repos.advisors),
      list: new ExecuteListAdvisors(executionContext, idGenerator, repos.advisors),
      update: new ExecuteUpdateAdvisor(executionContext, idGenerator, repos.advisors),
    },
    modelVersions: {
      create: new ExecuteCreateModelVersion(executionContext, idGenerator, repos.modelVersions),
      get: new ExecuteGetModelVersion(executionContext, idGenerator, repos.modelVersions),
      list: new ExecuteListModelVersions(executionContext, idGenerator, repos.modelVersions),
    },
    strategies: {
      create: new ExecuteCreateStrategy(executionContext, idGenerator, repos.strategies),
      get: new ExecuteGetStrategy(executionContext, idGenerator, repos.strategies),
      list: new ExecuteListStrategies(executionContext, idGenerator, repos.strategies),
      update: new ExecuteUpdateStrategy(executionContext, idGenerator, repos.strategies),
    },
  };
  return { repos, useCases: useCases as StrategiesDomainModule["useCases"] };
}
