/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { advisorRoutes } from "./advisor.routes.js";
export { modelVersionRoutes } from "./model-version.routes.js";
export { strategyRoutes } from "./strategy.routes.js";
