/**
 * Routes for Strategy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createStrategy, getStrategy, listStrategies, updateStrategy } from "../handlers/strategy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function strategyRoutes(fastify: FastifyInstance) {
  // POST /v1/strategies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/strategies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStrategiesDependenciesForRequest();
        await createStrategy(request, reply, deps);
      });
    }
  );


  // GET /v1/strategies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/strategies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStrategiesDependenciesForRequest();
        await listStrategies(request, reply, deps);
      });
    }
  );


  // GET /v1/strategies/{strategyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/strategies/:strategyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { strategyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStrategiesDependenciesForRequest();
        await getStrategy(request, reply, deps);
      });
    }
  );


  // PATCH /v1/strategies/{strategyId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/strategies/:strategyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { strategyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStrategiesDependenciesForRequest();
        await updateStrategy(request, reply, deps);
      });
    }
  );


}
