/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAuditDomainModule } from "./audit/dependencies/audit-ddd.dependencies.js";
export { buildFreezesDomainModule } from "./freezes/dependencies/freezes-ddd.dependencies.js";
export { buildGatesDomainModule } from "./gates/dependencies/gates-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildMarketplaceDomainModule } from "./marketplace/dependencies/marketplace-ddd.dependencies.js";
export { buildProfilesDomainModule } from "./profiles/dependencies/profiles-ddd.dependencies.js";
export { buildRecommendationsDomainModule } from "./recommendations/dependencies/recommendations-ddd.dependencies.js";
export { buildStrategiesDomainModule } from "./strategies/dependencies/strategies-ddd.dependencies.js";

// Export all domain dependency types
export type { AuditDomainModule } from "./audit/dependencies/audit-ddd.dependencies.js";
export type { FreezesDomainModule } from "./freezes/dependencies/freezes-ddd.dependencies.js";
export type { GatesDomainModule } from "./gates/dependencies/gates-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { MarketplaceDomainModule } from "./marketplace/dependencies/marketplace-ddd.dependencies.js";
export type { ProfilesDomainModule } from "./profiles/dependencies/profiles-ddd.dependencies.js";
export type { RecommendationsDomainModule } from "./recommendations/dependencies/recommendations-ddd.dependencies.js";
export type { StrategiesDomainModule } from "./strategies/dependencies/strategies-ddd.dependencies.js";
