/**
 * RecommendationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecommendationRepository Port
 *
 * DDD: Application port for recommendationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateClientRecommendationInput, CreateClientRecommendationOutput, GetRecommendationInput, GetRecommendationOutput, ListClientRecommendationsInput, ListClientRecommendationsOutput } from "../dto/recommendation.dto";
export interface RecommendationRepository {
  listClientRecommendations(input: ListClientRecommendationsInput): Promise<ListClientRecommendationsOutput>;
  createClientRecommendation(input: CreateClientRecommendationInput): Promise<CreateClientRecommendationOutput>;
  getRecommendation(input: GetRecommendationInput): Promise<GetRecommendationOutput>;
}

export type { CreateClientRecommendationInput, CreateClientRecommendationOutput, GetRecommendationInput, GetRecommendationOutput, ListClientRecommendationsInput, ListClientRecommendationsOutput } from "../dto/recommendation.dto";
