/**
 * Handlers for Contract
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MarketplaceDomainModule } from "../dependencies/marketplace-ddd.dependencies.js";
import type { CreateMarketplaceContractInput, GetMarketplaceContractInput, ListMarketplaceContractsInput } from "@veltara/services/marketplace";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/marketplace/contracts
 * Operation: listMarketplaceContracts
 */
export async function listMarketplaceContracts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { status?: string | string[], clientId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: MarketplaceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListMarketplaceContractsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.contracts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/marketplace/contracts
 * Operation: createMarketplaceContract
 */
export async function createMarketplaceContract(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: MarketplaceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateMarketplaceContractInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.contracts.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/marketplace/contracts/{contractId}
 * Operation: getMarketplaceContract
 */
export async function getMarketplaceContract(
  request: FastifyRequest<{ Params: { contractId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: MarketplaceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetMarketplaceContractInput = {
    contractId: request.params.contractId,
  };
  const result = await deps.useCases.contracts.get.execute(input);
  return reply.code(200).send(result);
}


