/**
 * ListGate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListGateDecisionsParams } from "@veltara/core/gates";

export function createListGateRequest(overrides: Partial<ListGateDecisionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
