/**
 * ListContract DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListMarketplaceContractsParams } from "@veltara/core/marketplace";

export function createListContractRequest(overrides: Partial<ListMarketplaceContractsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
