/**
 * FreezeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FreezeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FreezeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FreezeRepository,
} from "@veltara/services/freezes";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FreezeRepositoryDdb } from "./freeze-repository.ddb.js";

/**
 * FreezeRepositoryAdapter
 *
 * Implements FreezeRepository port for infrastructure layer.
 */
export class FreezeRepositoryAdapter implements FreezeRepository {
  private readonly ddb: FreezeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FreezeRepositoryDdb(this.dynamoClient);
  }

  async listFreezeOrders(input: Parameters<FreezeRepository['listFreezeOrders']>[0]): Promise<Awaited<ReturnType<FreezeRepository['listFreezeOrders']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFreezeOrders(input);
  }

  async createFreezeOrder(input: Parameters<FreezeRepository['createFreezeOrder']>[0]): Promise<Awaited<ReturnType<FreezeRepository['createFreezeOrder']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createFreezeOrder(input);
  }

  async getFreezeOrder(input: Parameters<FreezeRepository['getFreezeOrder']>[0]): Promise<Awaited<ReturnType<FreezeRepository['getFreezeOrder']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFreezeOrder(input);
  }
}
