/**
 * Gate Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { GateEntity } from "@veltara/core/gates/models/index.js";
import { gatesSchemas } from "@veltara/core/gates";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gat";

export function createGate(overrides: Partial<GateEntity> = {}) {
  const raw = {
    id: overrides.id ?? `gat_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    decidedAt: overrides.decidedAt ?? new Date().toISOString(),
    decidedBy: overrides.decidedBy ?? faker.lorem.word(),
    outcome: overrides.outcome ?? "pass",
    recommendationId: overrides.recommendationId ?? `rec_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return gatesSchemas.GateDecision.parse(raw);
}

export function gateBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createGate(overrides));
}
