/**
 * Freeze Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { FreezeEntity } from "@veltara/core/freezes/models/index.js";
import { freezesSchemas } from "@veltara/core/freezes";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "frz";

export function createFreeze(overrides: Partial<FreezeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `frz_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    issuedAt: overrides.issuedAt ?? new Date().toISOString(),
    issuedBy: overrides.issuedBy ?? faker.lorem.word(),
    reason: overrides.reason ?? faker.lorem.word(),
    status: overrides.status ?? "active",
    targetId: overrides.targetId ?? faker.string.uuid(),
    targetType: overrides.targetType ?? "strategy",
    ...overrides,
  };

  return freezesSchemas.FreezeOrder.parse(raw);
}

export function freezeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createFreeze(overrides));
}
