/**
 * ExecuteUpdateStrategy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateStrategy Use Case
 *
 * DDD: Application use case for update Strategy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateStrategyInput, UpdateStrategyOutput } from "../dto/strategy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { StrategyRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateStrategy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly strategy: StrategyRepository
  ) {}

  async execute(input: UpdateStrategyInput): Promise<UpdateStrategyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stgId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).strategyId) {
      throw new ValidationError("strategyId is required");
    }
    const strategyId = (input as any).strategyId;

    // Load existing entity
    const existing = await this.strategy.getStrategy({ strategyId: strategyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${strategyId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.strategy.updateStrategy({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateStrategyOutput;
  }
}
