/**
 * ExecuteGetAdvisor - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAdvisor Use Case
 *
 * DDD: Application use case for get Advisor.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAdvisorInput, GetAdvisorOutput } from "../dto/advisor.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { AdvisorRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAdvisor {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly advisor: AdvisorRepository
  ) {}

  async execute(input: GetAdvisorInput): Promise<GetAdvisorOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stgId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).advisorId) {
      throw new ValidationError("advisorId is required");
    }
    const advisorId = (input as any).advisorId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.advisor.getAdvisor({ advisorId: advisorId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${advisorId}`);
    }

    return entity as GetAdvisorOutput;
  }
}
