/**
 * ExecuteCreateStrategy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateStrategy Use Case
 *
 * DDD: Application use case for create Strategy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateStrategyInput, CreateStrategyOutput } from "../dto/strategy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { StrategyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateStrategy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly strategy: StrategyRepository
  ) {}

  async execute(input: CreateStrategyInput): Promise<CreateStrategyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.stgId();

    // All field names extracted from OpenAPI spec: advisorId, evidenceStatus, maxDrawdownClaim, modelVersionId, name, provenance, sharpeClaim, thesis
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.provenance) {
      throw new ValidationError("provenance is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (strategies domain)
    const entityId = this.idGenerator.stgId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.strategy.createStrategy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateStrategyOutput;
  }
}
