/**
 * ListClientRecommendations handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listClientRecommendations } from "@veltara/api-server/domains/recommendations/handlers";
import type { RecommendationsDDDDependencies } from "@veltara/api-server/domains/recommendations";
import { createRecommendation as createRecommendationEntity } from "@veltara/factories/recommendations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { RECOMMENDATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListClientRecommendations", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RecommendationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RecommendationsDDDDependencies>(
      RECOMMENDATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createRecommendationEntity({ orgId }),
      createRecommendationEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListClientRecommendations, "execute").mockResolvedValue(useCaseResult);

    await listClientRecommendations(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListClientRecommendations.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
