/**
 * SuitabilityPolicy Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SuitabilityPolicyEntity } from "@veltara/core/profiles/models/index.js";
import { profilesSchemas } from "@veltara/core/profiles";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prf";

export function createSuitabilityPolicy(overrides: Partial<SuitabilityPolicyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `pol_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    rulesSummary: overrides.rulesSummary ?? faker.lorem.word(),
    status: overrides.status ?? "active",
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return profilesSchemas.SuitabilityPolicy.parse(raw);
}

export function suitabilityPolicyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSuitabilityPolicy(overrides));
}
