/**
 * Contract Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/marketplace.openapi.types.js";
import { schemas } from "../schemas/marketplace.schemas.js";

/**
 * Entity: ContractEntity
 * Description: Represents the Contract domain model.
 * Source: schemas.MarketplaceContract
 * Type: Persisted Entity (x-dynamodb)
 */
export const ContractEntitySchema = schemas.MarketplaceContract;
export type ContractEntity = components["schemas"]["MarketplaceContract"];
