/**
 * RecommendationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RecommendationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RecommendationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RecommendationRepository,
} from "@veltara/services/recommendations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RecommendationRepositoryDdb } from "./recommendation-repository.ddb.js";

/**
 * RecommendationRepositoryAdapter
 *
 * Implements RecommendationRepository port for infrastructure layer.
 */
export class RecommendationRepositoryAdapter implements RecommendationRepository {
  private readonly ddb: RecommendationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RecommendationRepositoryDdb(this.dynamoClient);
  }

  async listClientRecommendations(input: Parameters<RecommendationRepository['listClientRecommendations']>[0]): Promise<Awaited<ReturnType<RecommendationRepository['listClientRecommendations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listClientRecommendations(input);
  }

  async createClientRecommendation(input: Parameters<RecommendationRepository['createClientRecommendation']>[0]): Promise<Awaited<ReturnType<RecommendationRepository['createClientRecommendation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createClientRecommendation(input);
  }

  async getRecommendation(input: Parameters<RecommendationRepository['getRecommendation']>[0]): Promise<Awaited<ReturnType<RecommendationRepository['getRecommendation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRecommendation(input);
  }
}
