/**
 * Repository interface for Freeze
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  FreezeEntity
} from "../models/freeze.entity.js";
import type {
  ListFreezeOrdersParams,
  FreezeOrder
} from "../types/index.js";
/**
 * FreezeRepository Interface
 */
export interface FreezeRepository extends CreateReadRepository<FreezeEntity, FreezeOrder, string, ListFreezeOrdersParams> {

}
