/**
 * Repository interface for Profile
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ProfileEntity
} from "../models/profile.entity.js";
import type {
  UpsertClientProfileRequestInput
} from "../types/index.js";
/**
 * ProfileRepository Interface
 */
export interface ProfileRepository extends UpdateReadRepository<ProfileEntity, UpsertClientProfileRequestInput, string, Record<string, never>> {

}
