/**
 * ExecuteCreateClientRecommendation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateClientRecommendation Use Case
 *
 * DDD: Application use case for create Recommendation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateClientRecommendationInput, CreateClientRecommendationOutput } from "../dto/recommendation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { RecommendationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateClientRecommendation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly recommendation: RecommendationRepository
  ) {}

  async execute(input: CreateClientRecommendationInput): Promise<CreateClientRecommendationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.recId();

    // All field names extracted from OpenAPI spec: explanation, matchReasons, rankingScore, strategyId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.strategyId) {
      throw new ValidationError("strategyId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (recommendations domain)
    const entityId = this.idGenerator.recId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.recommendation.createClientRecommendation({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateClientRecommendationOutput;
  }
}
