/**
 * ExecuteUpsertRecommendationRiskParameters - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertRecommendationRiskParameters Use Case
 *
 * DDD: Application use case for get RiskParameter.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertRecommendationRiskParametersInput, UpsertRecommendationRiskParametersOutput } from "../dto/risk-parameter.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { RiskParameterRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteUpsertRecommendationRiskParameters {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly riskParameter: RiskParameterRepository
  ) {}

  async execute(input: UpsertRecommendationRiskParametersInput): Promise<UpsertRecommendationRiskParametersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.recId();

    // All field names extracted from OpenAPI spec: concentrationNote, hedgeSuggestions, maxLossPct, targetProbability
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).recommendationId) {
      throw new ValidationError("recommendationId is required");
    }
    const recommendationId = (input as any).recommendationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.riskParameter.upsertRecommendationRiskParameters({ recommendationId: recommendationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${recommendationId}`);
    }

    return entity as UpsertRecommendationRiskParametersOutput;
  }
}
