/**
 * Handlers for Advisor
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { StrategiesDomainModule } from "../dependencies/strategies-ddd.dependencies.js";
import type { CreateAdvisorInput, GetAdvisorInput, ListAdvisorsInput, UpdateAdvisorInput } from "@veltara/services/strategies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/advisors
 * Operation: listAdvisors
 */
export async function listAdvisors(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAdvisorsInput = {};
  const result = await deps.useCases.advisors.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/advisors
 * Operation: createAdvisor
 */
export async function createAdvisor(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAdvisorInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.advisors.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/advisors/{advisorId}
 * Operation: getAdvisor
 */
export async function getAdvisor(
  request: FastifyRequest<{ Params: { advisorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAdvisorInput = {
    advisorId: request.params.advisorId,
  };
  const result = await deps.useCases.advisors.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/advisors/{advisorId}
 * Operation: updateAdvisor
 */
export async function updateAdvisor(
  request: FastifyRequest<{ Params: { advisorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateAdvisorInput = {
    advisorId: request.params.advisorId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.advisors.update.execute(input);
  return reply.code(200).send(result);
}


