/**
 * Handlers for ModelVersion
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { StrategiesDomainModule } from "../dependencies/strategies-ddd.dependencies.js";
import type { CreateModelVersionInput, GetModelVersionInput, ListModelVersionsInput } from "@veltara/services/strategies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/model-versions
 * Operation: listModelVersions
 */
export async function listModelVersions(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListModelVersionsInput = {};
  const result = await deps.useCases.modelVersions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/model-versions
 * Operation: createModelVersion
 */
export async function createModelVersion(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateModelVersionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.modelVersions.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/model-versions/{modelVersionId}
 * Operation: getModelVersion
 */
export async function getModelVersion(
  request: FastifyRequest<{ Params: { modelVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetModelVersionInput = {
    modelVersionId: request.params.modelVersionId,
  };
  const result = await deps.useCases.modelVersions.get.execute(input);
  return reply.code(200).send(result);
}


