/**
 * ExecuteDecideRecommendationGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDecideRecommendationGate Use Case
 *
 * DDD: Application use case for get Gate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DecideRecommendationGateInput, DecideRecommendationGateOutput } from "../dto/gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { GateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDecideRecommendationGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly gate: GateRepository
  ) {}

  async execute(input: DecideRecommendationGateInput): Promise<DecideRecommendationGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gatId();

    // All field names extracted from OpenAPI spec: outcome, overrideJustification, reasons, secondApproverId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).recommendationId) {
      throw new ValidationError("recommendationId is required");
    }
    const recommendationId = (input as any).recommendationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.gate.decideRecommendationGate({ recommendationId: recommendationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${recommendationId}`);
    }

    return entity as DecideRecommendationGateOutput;
  }
}
