/**
 * ListFreeze DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListFreezeOrdersParams } from "@veltara/core/freezes";

export function createListFreezeRequest(overrides: Partial<ListFreezeOrdersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
