/**
 * ExecuteGetClientProfile - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetClientProfile Use Case
 *
 * DDD: Application use case for get Profile.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetClientProfileInput, GetClientProfileOutput } from "../dto/profile.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { ProfileRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetClientProfile {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly profile: ProfileRepository
  ) {}

  async execute(input: GetClientProfileInput): Promise<GetClientProfileOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prfId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).clientId) {
      throw new ValidationError("clientId is required");
    }
    const clientId = (input as any).clientId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.profile.getClientProfile({ clientId: clientId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${clientId}`);
    }

    return entity as GetClientProfileOutput;
  }
}
