/**
 * ExecuteCreateSuitabilityPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateSuitabilityPolicy Use Case
 *
 * DDD: Application use case for create SuitabilityPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateSuitabilityPolicyInput, CreateSuitabilityPolicyOutput } from "../dto/suitability-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@veltara/services/_shared/index.js";
import type { SuitabilityPolicyRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateSuitabilityPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly suitabilityPolicy: SuitabilityPolicyRepository
  ) {}

  async execute(input: CreateSuitabilityPolicyInput): Promise<CreateSuitabilityPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prfId();

    // All field names extracted from OpenAPI spec: maxRiskScore, name, requireHumanGate, rulesSummary, status, version
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.version) {
      throw new ValidationError("version is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.rulesSummary) {
      throw new ValidationError("rulesSummary is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (profiles domain)
    const entityId = this.idGenerator.prfId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.suitabilityPolicy.createSuitabilityPolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateSuitabilityPolicyOutput;
  }
}
