/**
 * GetGateDecision handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getGateDecision } from "@veltara/api-server/domains/gates/handlers";
import type { GatesDDDDependencies } from "@veltara/api-server/domains/gates";
import { createGate as createGateEntity } from "@veltara/factories/gates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { GATES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetGateDecision", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GatesDDDDependencies>(
      GATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createGateEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetGateDecision, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { gateDecisionId: entity.id };

    await getGateDecision(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetGateDecision.execute).toHaveBeenCalledWith(expect.objectContaining({ gateDecisionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { gateDecisionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetGateDecision, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getGateDecision(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
