/**
 * UpsertClientProfile handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { upsertClientProfile } from "@veltara/api-server/domains/profiles/handlers";
import type { ProfilesDDDDependencies } from "@veltara/api-server/domains/profiles";
import { createProfile as createProfileEntity } from "@veltara/factories/profiles";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@veltara/tests/shared";
import { PROFILES_USE_CASES } from "../__factories__/use-cases.js";

describe("UpsertClientProfile", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProfilesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProfilesDDDDependencies>(
      PROFILES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createProfileEntity({ orgId });
    const input = {} as any;
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { clientId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpsertClientProfile, "execute").mockResolvedValue(useCaseResult);

    await upsertClientProfile(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpsertClientProfile.execute).toHaveBeenCalledWith(expect.objectContaining({ clientId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
