/**
 * Handlers for Recommendation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RecommendationsDomainModule } from "../dependencies/recommendations-ddd.dependencies.js";
import type { CreateClientRecommendationInput, GetRecommendationInput, ListClientRecommendationsInput } from "@veltara/services/recommendations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/clients/{clientId}/recommendations
 * Operation: listClientRecommendations
 */
export async function listClientRecommendations(
  request: FastifyRequest<{ Params: { clientId: string }; Querystring: { status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: RecommendationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListClientRecommendationsInput = {
    clientId: request.params.clientId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.recommendations.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/clients/{clientId}/recommendations
 * Operation: createClientRecommendation
 */
export async function createClientRecommendation(
  request: FastifyRequest<{ Params: { clientId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RecommendationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateClientRecommendationInput = {
    clientId: request.params.clientId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.recommendations.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/recommendations/{recommendationId}
 * Operation: getRecommendation
 */
export async function getRecommendation(
  request: FastifyRequest<{ Params: { recommendationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RecommendationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRecommendationInput = {
    recommendationId: request.params.recommendationId,
  };
  const result = await deps.useCases.recommendations.get.execute(input);
  return reply.code(200).send(result);
}


