/**
 * ContractRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: marketplace
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContractRepository Port
 *
 * DDD: Application port for contractrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateMarketplaceContractInput, CreateMarketplaceContractOutput, GetMarketplaceContractInput, GetMarketplaceContractOutput, ListMarketplaceContractsInput, ListMarketplaceContractsOutput } from "../dto/contract.dto";
export interface ContractRepository {
  listMarketplaceContracts(input: ListMarketplaceContractsInput): Promise<ListMarketplaceContractsOutput>;
  createMarketplaceContract(input: CreateMarketplaceContractInput): Promise<CreateMarketplaceContractOutput>;
  getMarketplaceContract(input: GetMarketplaceContractInput): Promise<GetMarketplaceContractOutput>;
}

export type { CreateMarketplaceContractInput, CreateMarketplaceContractOutput, GetMarketplaceContractInput, GetMarketplaceContractOutput, ListMarketplaceContractsInput, ListMarketplaceContractsOutput } from "../dto/contract.dto";
