/**
 * Recommendations Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: recommendations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createClientRecommendation_Body = z
  .object({
    strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
    matchReasons: z.array(z.string()).optional(),
    explanation: z.string().optional(),
    rankingScore: z.number().optional(),
  })
  .passthrough();
const upsertRecommendationRiskParameters_Body = z
  .object({
    maxLossPct: z.number().gte(0).lte(100),
    targetProbability: z.number().gte(0).lte(1).optional(),
    hedgeSuggestions: z.array(z.string()).optional(),
    concentrationNote: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  createClientRecommendation_Body,
  upsertRecommendationRiskParameters_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/clients/:clientId/recommendations',
    alias: 'listClientRecommendations',
    requestFormat: 'json',
    parameters: [
      {
        name: 'clientId',
        type: 'Path',
        schema: z.string().regex(/^cli_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['pending_gate', 'approved', 'blocked', 'superseded'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string().regex(/^rec_[0-9A-HJKMNP-TV-Z]{26}$/),
                  clientId: z.string().regex(/^cli_[0-9A-HJKMNP-TV-Z]{26}$/),
                  strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
                  matchReasons: z.array(z.string()).optional(),
                  explanation: z.string().optional(),
                  rankingScore: z.number().optional(),
                  status: z.enum([
                    'pending_gate',
                    'approved',
                    'blocked',
                    'superseded',
                  ]),
                  riskParameterSetId: z
                    .string()
                    .regex(/^rsk_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/clients/:clientId/recommendations',
    alias: 'createClientRecommendation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createClientRecommendation_Body,
      },
      {
        name: 'clientId',
        type: 'Path',
        schema: z.string().regex(/^cli_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^rec_[0-9A-HJKMNP-TV-Z]{26}$/),
            clientId: z.string().regex(/^cli_[0-9A-HJKMNP-TV-Z]{26}$/),
            strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
            matchReasons: z.array(z.string()).optional(),
            explanation: z.string().optional(),
            rankingScore: z.number().optional(),
            status: z.enum([
              'pending_gate',
              'approved',
              'blocked',
              'superseded',
            ]),
            riskParameterSetId: z
              .string()
              .regex(/^rsk_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/recommendations/:recommendationId',
    alias: 'getRecommendation',
    requestFormat: 'json',
    parameters: [
      {
        name: 'recommendationId',
        type: 'Path',
        schema: z.string().regex(/^rec_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^rec_[0-9A-HJKMNP-TV-Z]{26}$/),
            clientId: z.string().regex(/^cli_[0-9A-HJKMNP-TV-Z]{26}$/),
            strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
            matchReasons: z.array(z.string()).optional(),
            explanation: z.string().optional(),
            rankingScore: z.number().optional(),
            status: z.enum([
              'pending_gate',
              'approved',
              'blocked',
              'superseded',
            ]),
            riskParameterSetId: z
              .string()
              .regex(/^rsk_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/recommendations/:recommendationId/risk-parameters',
    alias: 'getRecommendationRiskParameters',
    requestFormat: 'json',
    parameters: [
      {
        name: 'recommendationId',
        type: 'Path',
        schema: z.string().regex(/^rec_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^rsk_[0-9A-HJKMNP-TV-Z]{26}$/),
            recommendationId: z.string().regex(/^rec_[0-9A-HJKMNP-TV-Z]{26}$/),
            maxLossPct: z.number().gte(0).lte(100),
            targetProbability: z.number().gte(0).lte(1).optional(),
            hedgeSuggestions: z.array(z.string()).optional(),
            concentrationNote: z.string().optional(),
            status: z.enum(['draft', 'attached', 'overridden']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'put',
    path: '/v1/recommendations/:recommendationId/risk-parameters',
    alias: 'upsertRecommendationRiskParameters',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: upsertRecommendationRiskParameters_Body,
      },
      {
        name: 'recommendationId',
        type: 'Path',
        schema: z.string().regex(/^rec_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string().regex(/^rsk_[0-9A-HJKMNP-TV-Z]{26}$/),
            recommendationId: z.string().regex(/^rec_[0-9A-HJKMNP-TV-Z]{26}$/),
            maxLossPct: z.number().gte(0).lte(100),
            targetProbability: z.number().gte(0).lte(1).optional(),
            hedgeSuggestions: z.array(z.string()).optional(),
            concentrationNote: z.string().optional(),
            status: z.enum(['draft', 'attached', 'overridden']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
