/**
 * Freeze Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: freezes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/freezes.openapi.types.js";
import { schemas } from "../schemas/freezes.schemas.js";

/**
 * Entity: FreezeEntity
 * Description: Represents the Freeze domain model.
 * Source: schemas.FreezeOrder
 * Type: Persisted Entity (x-dynamodb)
 */
export const FreezeEntitySchema = schemas.FreezeOrder;
export type FreezeEntity = components["schemas"]["FreezeOrder"];
