/**
 * Profile DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Profile DTOs
 *
 * DDD: Application DTOs for Profile use cases.
 */

import type { GetClientProfileParams, UpsertClientProfileParams, UpsertClientProfileRequestInput } from "@veltara/core/profiles/types";

export type GetClientProfileInput = GetClientProfileParams;

export type UpsertClientProfileInput = UpsertClientProfileParams & UpsertClientProfileRequestInput;

export type GetClientProfileOutput = {};

export type UpsertClientProfileOutput = {};
