/**
 * SuitabilityPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: profiles
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SuitabilityPolicy DTOs
 *
 * DDD: Application DTOs for SuitabilityPolicy use cases.
 */

import type { CreateSuitabilityPolicyRequestInput, GetSuitabilityPolicyParams, UpsertSuitabilityPolicyParams, UpsertSuitabilityPolicyRequestInput } from "@veltara/core/profiles/types";

export type ListSuitabilityPoliciesInput = {};

export type CreateSuitabilityPolicyInput = CreateSuitabilityPolicyRequestInput;

export type GetSuitabilityPolicyInput = GetSuitabilityPolicyParams;

export type UpsertSuitabilityPolicyInput = UpsertSuitabilityPolicyParams & UpsertSuitabilityPolicyRequestInput;

export type ListSuitabilityPoliciesOutput = {};

export type CreateSuitabilityPolicyOutput = {};

export type GetSuitabilityPolicyOutput = {};

export type UpsertSuitabilityPolicyOutput = {};
